name: Test

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: mkdir build

      - name: Configure
        run: cmake ..
        working-directory: build/

      - name: Build
        run: cmake --build test/
        working-directory: build/

      - name: Test
        run: ctest -C debug --test-dir test/
        working-directory: build/

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: test-result
          path: build/test/CMakeFiles/*.dir/**/*.gc*
          retention-days: 1

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download test result
        uses: actions/download-artifact@v3
        with:
          name: test-result

      - name: Generate coverage.info
        run: lcov -d . -c -o coverage.info

      - name: Filter coverage.info
        run: lcov -r coverage.info '*/c++/*' '*/catch2/*' '*/test/*' -o coverage.info

      - name: Print coverage
        run: lcov -l coverage.info
